import crypto from "crypto"

const SECRET = process.env.VB_TEMPLATE_SECRET || "fallback-dev-secret"
const MARKER = "#VB-SIGNED"

/**
 * Generate an HMAC-SHA256 signature for a given org + election combination.
 * The signature is deterministic — same inputs always produce the same signature.
 */
export function generateSignature(orgId, electionId) {
  return crypto
    .createHmac("sha256", SECRET)
    .update(`${orgId}:${electionId}`)
    .digest("hex")
}

/**
 * Build the two special rows that go at the top of every official template.
 * Row 1: machine-readable signed marker (starts with # so CSV parsers skip it)
 * Row 2: human-readable watermark (also starts with # so CSV parsers skip it)
 */
export function buildSignatureRows(orgId, electionId, orgName, electionName) {
  const sig = generateSignature(orgId, electionId)
  const date = new Date().toISOString().slice(0, 10)
  const sigRow = `${MARKER}:${orgId}:${electionId}:${sig}`
  const watermarkRow = `# Official Virtual Ballot Roster Template | ${orgName} | ${electionName} | Generated: ${date} | Do not edit this line`
  return { sigRow, watermarkRow }
}

/**
 * Extract and verify the signature from a raw CSV string.
 * Returns { valid: true, orgId, electionId } or { valid: false, reason: string }
 */
export function verifyCSVSignature(rawCSV) {
  const lines = rawCSV.split("\n").map((l) => l.trim()).filter(Boolean)

  // Find the signature row — it must be a marker line at the top of the file.
  const sigLine = lines.find((l) => l.startsWith(MARKER))
  if (!sigLine) {
    return {
      valid: false,
      reason:
        "This file was not generated by Virtual Ballot. Please download the official template from the Voters tab.",
    }
  }

  // Format: #VB-SIGNED:orgId:electionId:signature
  // UUIDs contain hyphens (not colons), so a simple split on ":" is safe.
  const parts = sigLine.split(":")
  if (parts.length < 4) {
    return {
      valid: false,
      reason: "Invalid template signature format. Please download a fresh template.",
    }
  }

  const [, embeddedOrgId, embeddedElectionId, embeddedSig] = parts
  if (!embeddedOrgId || !embeddedElectionId || !embeddedSig) {
    return {
      valid: false,
      reason: "Malformed template signature. Please download a fresh template.",
    }
  }

  const expectedSig = generateSignature(embeddedOrgId, embeddedElectionId)

  // Constant-time comparison to avoid leaking signature bytes via timing.
  let expected
  let received
  try {
    expected = Buffer.from(expectedSig, "hex")
    received = Buffer.from(embeddedSig, "hex")
  } catch {
    return {
      valid: false,
      reason:
        "Template signature is invalid. This file may have been tampered with or was not generated by this system.",
    }
  }

  if (
    expected.length !== received.length ||
    !crypto.timingSafeEqual(expected, received)
  ) {
    return {
      valid: false,
      reason:
        "Template signature is invalid. This file may have been tampered with or was not generated by this system.",
    }
  }

  return { valid: true, orgId: embeddedOrgId, electionId: embeddedElectionId }
}

/**
 * Strip the signature and watermark rows from a raw CSV before parsing voter rows.
 * Returns only the data rows (including the matric,name,email header row).
 */
export function stripSignatureRows(rawCSV) {
  return rawCSV
    .split("\n")
    .filter((line) => !line.trim().startsWith("#"))
    .join("\n")
}
