import { useState } from "react";
import {
  Upload,
  Users,
  FileDown,
  Search,
  UserCheck,
  UserX,
  Copy,
  Check,
  ClipboardList,
  Lock,
  Flag,
  UserPlus,
  RotateCcw,
  ShieldCheck,
} from "lucide-react";
import { useApp } from "../../context/AppContext";
import { buildVoterCSV, downloadCSV, getTurnout } from "../../utils";
import {
  uploadRoster,
  downloadRosterTemplate,
  fetchVoters,
  removeVoter,
  resolveRosterFlag,
  regenerateReviewCodes,
  updateElectionConfig,
  addRosterReviewer,
  removeRosterReviewer,
} from "../../api";
import VBLoader from "../ui/VBLoader";

export default function VotersTab() {
  const {
    users,
    setUsers,
    accessToken,
    orgSlug,
    showAlert,
    showConfirm,
    addLog,
    electionConfig,
    setElectionConfig,
    rosterApproval,
    refreshRosterApproval,
    mapVoter,
  } = useApp();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const [uploading, setUploading] = useState(false);
  const [replaceMode, setReplaceMode] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copiedObs, setCopiedObs] = useState(false);
  const [codesCopied, setCodesCopied] = useState(false);
  const [copiedId, setCopiedId] = useState(null);
  const [approvalBusy, setApprovalBusy] = useState(false);
  const [reviewerName, setReviewerName] = useState("");

  const rosterActive = electionConfig.votingMode === "CLOSED";

  const voterUrl = `${window.location.origin}/vote/${orgSlug}`;
  const observerUrl = `${window.location.origin}/observer/login?slug=${orgSlug}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(voterUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleCopyObs = () => {
    navigator.clipboard.writeText(observerUrl).then(() => {
      setCopiedObs(true);
      setTimeout(() => setCopiedObs(false), 2000);
    });
  };

  const voters = users.filter((u) => u.role !== "ADMIN");
  const voted = voters.filter((u) => u.hasVoted);
  const pending = voters.filter((u) => !u.hasVoted);
  const { pct, accredited } = getTurnout(users);

  const filtered = voters.filter((u) => {
    const matchText =
      u.matric.toLowerCase().includes(search.toLowerCase()) ||
      u.name.toLowerCase().includes(search.toLowerCase());
    const matchFilter =
      filter === "all" ||
      (filter === "accredited" && u.email) ||
      (filter === "voted" && u.hasVoted) ||
      (filter === "pending" && !u.hasVoted);
    return matchText && matchFilter;
  });

  const exportCSV = () => downloadCSV(buildVoterCSV(voters), "registry.csv");

  // Download the official signed template.
  const handleDownloadTemplate = async () => {
    try {
      const csvText = await downloadRosterTemplate(accessToken, orgSlug);
      const blob = new Blob([csvText], { type: "text/csv" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `roster-template-${orgSlug}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      showAlert("Download Failed", err.message);
    }
  };

  // Upload the raw (signed) CSV → backend verifies the signature before parsing.
  const upload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    e.target.value = "";
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const csvRaw = ev.target.result;

      // Fast client-side check — the backend does the real cryptographic verify.
      if (!csvRaw.includes("#VB-SIGNED")) {
        showAlert(
          "Invalid Template",
          "This file was not generated by Virtual Ballot. Please click 'Download Template' to get the official template, fill it in, and upload that file."
        );
        return;
      }

      setUploading(true);
      try {
        const result = await uploadRoster(
          csvRaw,
          accessToken,
          orgSlug,
          replaceMode
        );
        // Refresh the voter list from the backend (source of truth).
        try {
          const data = await fetchVoters(accessToken, orgSlug);
          setUsers((data.voters || []).map(mapVoter));
        } catch (_) {}

        addLog(
          replaceMode
            ? `Roster replaced — ${result.inserted} voters loaded`
            : `Roster updated — ${result.inserted} voters added`,
          "registry"
        );
        showAlert(
          replaceMode ? "Roster Replaced" : "Upload Success",
          replaceMode
            ? `${result.inserted} voters loaded. Voters who already voted were preserved.`
            : `${result.inserted} voters added to roster. ${result.skipped} skipped (duplicates).`
        );
        // Closed elections: refresh the review panel (a changed roster may
        // reset the approval status). Open elections are unaffected.
        if (rosterActive) refreshRosterApproval();
      } catch (err) {
        showAlert("Upload Failed", err.message);
      } finally {
        setUploading(false);
      }
    };
    reader.readAsText(file);
  };

  const handleRemove = async (voter) => {
    try {
      await removeVoter(voter.id, accessToken, orgSlug);
      setUsers((prev) => prev.filter((u) => u.matric !== voter.matric));
      addLog(`Voter ${voter.matric} removed from roster`, "registry");
    } catch (err) {
      showAlert("Cannot Remove", err.message);
    }
  };

  // ── Roster review panel helpers ─────────────────────────────────────────────
  // Flatten every flag with the reviewer who raised it for the flags table.
  const allFlags = rosterApproval.approvals.flatMap((a) =>
    (a.flags || []).map((f) => ({ ...f, reviewer: a.reviewerName }))
  );
  const unresolvedFlags = allFlags.filter((f) => !f.resolved);

  const handleAddReviewer = async () => {
    const name = reviewerName.trim();
    if (!name) return;
    setApprovalBusy(true);
    try {
      await addRosterReviewer(name, accessToken, orgSlug);
      await refreshRosterApproval();
      addLog(`Committee member '${name}' added to roster review panel`, "registry");
      setReviewerName("");
    } catch (err) {
      showAlert("Could Not Add Reviewer", err.message);
    } finally {
      setApprovalBusy(false);
    }
  };

  const handleRemoveReviewer = (reviewer) => {
    showConfirm(
      "Remove committee member?",
      `Remove ${reviewer.reviewerName} from the review panel? Their review code will stop working.`,
      async () => {
        setApprovalBusy(true);
        try {
          await removeRosterReviewer(reviewer.id, accessToken, orgSlug);
          await refreshRosterApproval();
          addLog(
            `Committee member '${reviewer.reviewerName}' removed from roster review panel`,
            "registry"
          );
        } catch (err) {
          showAlert("Could Not Remove", err.message);
        } finally {
          setApprovalBusy(false);
        }
      }
    );
  };

  const copyAllCodes = () => {
    const lines = rosterApproval.approvals
      .map((a) => `${a.reviewerName}: ${a.reviewCode}`)
      .join("\n");
    const text = `Virtual Ballot — Roster Review Panel
Please use your personal code to review the voter list.

Review Portal: ${window.location.origin}/roster-review

${lines}`;
    navigator.clipboard.writeText(text).then(() => {
      setCodesCopied(true);
      setTimeout(() => setCodesCopied(false), 2500);
    });
  };

  // Copy one reviewer's personal invite (portal link + their code) to send individually.
  const copyReviewer = (a) => {
    const text = `Hi ${a.reviewerName}, please review and approve the voter list for the election.

Review Portal: ${window.location.origin}/roster-review
Your code: ${a.reviewCode}`;
    navigator.clipboard.writeText(text).then(() => {
      setCopiedId(a.id);
      setTimeout(() => setCopiedId((cur) => (cur === a.id ? null : cur)), 2500);
    });
  };

  const handleResetApprovals = () => {
    showConfirm(
      "Reset all approvals?",
      "This sets every committee member back to pending. They keep their codes but must review and approve again. Continue?",
      async () => {
        setApprovalBusy(true);
        try {
          await regenerateReviewCodes(accessToken, orgSlug);
          await refreshRosterApproval();
          addLog("Roster approvals reset — all committee members must re-approve", "registry");
        } catch (err) {
          showAlert("Reset Failed", err.message);
        } finally {
          setApprovalBusy(false);
        }
      }
    );
  };

  const handleResolveFlag = async (flagId, matric) => {
    setApprovalBusy(true);
    try {
      await resolveRosterFlag(flagId, accessToken, orgSlug);
      await refreshRosterApproval();
      addLog(`Flag on matric ${matric} resolved`, "admin");
    } catch (err) {
      showAlert("Could Not Resolve", err.message);
    } finally {
      setApprovalBusy(false);
    }
  };

  const handleLockRegistry = () => {
    if (!rosterApproval.allApproved || rosterApproval.hasUnresolvedFlags) return;
    showConfirm(
      "Lock the registry?",
      "All committee members have approved the voter list. Locking the registry finalises it so it can no longer be edited before voting. Continue?",
      async () => {
        setApprovalBusy(true);
        try {
          await updateElectionConfig(
            { registryLocked: true },
            accessToken,
            orgSlug
          );
          setElectionConfig((prev) => ({ ...prev, registryLocked: true }));
          addLog("Registry locked — roster approved by all committee members", "registry");
          showAlert(
            "Registry Locked",
            "The voter registry is now locked. You can start the election from the Election tab."
          );
        } catch (err) {
          showAlert("Could Not Lock Registry", err.message);
        } finally {
          setApprovalBusy(false);
        }
      }
    );
  };

  return (
    <div className="space-y-5">
      {/* ── Roster review panel (closed elections only) ────────────────────── */}
      {rosterActive && (
        <div className="bg-slate-800 rounded-2xl border border-slate-700 overflow-hidden">
          <div className="p-5 border-b border-slate-700">
            <div className="flex items-center gap-2 mb-4">
              <ClipboardList className="w-5 h-5 text-slate-400" />
              <h3 className="text-white font-black uppercase tracking-widest text-sm">
                Roster Review Panel
              </h3>
            </div>

            {/* Add a committee member */}
            <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2">
              Add a committee member
            </p>
            <div className="flex gap-3">
              <input
                value={reviewerName}
                onChange={(e) => setReviewerName(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleAddReviewer()}
                placeholder="Full name (e.g. Kabir Marzooq)"
                className="flex-1 bg-slate-900 border border-slate-600 rounded-xl px-4 py-3 text-sm text-white outline-none focus:border-blue-500 placeholder:text-slate-600"
              />
              <button
                onClick={handleAddReviewer}
                disabled={approvalBusy || !reviewerName.trim()}
                className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-5 rounded-xl flex items-center gap-2 transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed whitespace-nowrap"
              >
                <UserPlus className="w-4 h-4" /> Add Reviewer
              </button>
            </div>

            {/* Progress */}
            {rosterApproval.totalCount > 0 && (
              <div className="mt-5">
                <div className="flex justify-between items-center mb-2">
                  <p className="text-sm font-bold text-slate-300">
                    {rosterApproval.approvedCount} of {rosterApproval.totalCount}{" "}
                    reviewers have approved
                  </p>
                  <p className="text-sm font-mono font-bold text-white">
                    {Math.round(
                      (rosterApproval.approvedCount / rosterApproval.totalCount) *
                        100
                    )}
                    %
                  </p>
                </div>
                <div className="w-full bg-slate-700 rounded-full h-3">
                  <div
                    className="bg-blue-500 h-3 rounded-full transition-all duration-700"
                    style={{
                      width: `${
                        (rosterApproval.approvedCount /
                          rosterApproval.totalCount) *
                        100
                      }%`,
                    }}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Reviewer table */}
          {rosterApproval.approvals.length === 0 ? (
            <p className="text-slate-500 text-sm text-center py-8 px-5">
              No committee members yet. Add reviewers above, then send each
              person their code and the review portal link.
            </p>
          ) : (
            <>
              <div className="grid grid-cols-12 gap-2 px-5 py-2 text-xs font-bold text-slate-500 uppercase tracking-widest border-b border-slate-700/50">
                <span className="col-span-4">Reviewer</span>
                <span className="col-span-2">Code</span>
                <span className="col-span-2">Status</span>
                <span className="col-span-2">Approved At</span>
                <span className="col-span-2 text-right">Actions</span>
              </div>
              <div className="divide-y divide-slate-700/40">
                {rosterApproval.approvals.map((a) => (
                  <div
                    key={a.id}
                    className="grid grid-cols-12 gap-2 px-5 py-3 items-center"
                  >
                    <span className="col-span-4 text-sm font-bold text-white truncate">
                      {a.reviewerName}
                    </span>
                    <span className="col-span-2 font-mono text-xs text-slate-300 tracking-widest">
                      {a.reviewCode}
                    </span>
                    <div className="col-span-2 flex items-center gap-2">
                      <span
                        className={`w-2 h-2 rounded-full ${
                          a.approved ? "bg-blue-400" : "bg-amber-500"
                        }`}
                      />
                      <span className="text-xs text-slate-400">
                        {a.approved ? "Approved" : "Pending"}
                      </span>
                    </div>
                    <span className="col-span-2 text-xs text-slate-500">
                      {a.approvedAt
                        ? new Date(a.approvedAt).toLocaleTimeString([], {
                            hour: "2-digit",
                            minute: "2-digit",
                          })
                        : "—"}
                    </span>
                    <div className="col-span-2 flex justify-end items-center gap-3">
                      <button
                        onClick={() => copyReviewer(a)}
                        title="Copy this reviewer's link + code"
                        className={`text-xs font-bold flex items-center gap-1 transition-colors cursor-pointer ${
                          copiedId === a.id
                            ? "text-green-400"
                            : "text-slate-400 hover:text-blue-300"
                        }`}
                      >
                        {copiedId === a.id ? (
                          <>
                            <Check className="w-3.5 h-3.5" /> Copied
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" /> Copy
                          </>
                        )}
                      </button>
                      {!a.approved && (
                        <button
                          onClick={() => handleRemoveReviewer(a)}
                          disabled={approvalBusy}
                          className="text-red-400 hover:text-red-300 text-xs font-bold transition-colors cursor-pointer disabled:opacity-50"
                        >
                          Remove
                        </button>
                      )}
                    </div>
                  </div>
                ))}
              </div>

              {/* Actions */}
              <div className="p-5 border-t border-slate-700 flex flex-wrap gap-3">
                <button
                  onClick={copyAllCodes}
                  className={`flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-xl transition-all cursor-pointer ${
                    codesCopied
                      ? "bg-slate-600 text-white"
                      : "bg-slate-700 hover:bg-slate-600 text-slate-300"
                  }`}
                >
                  {codesCopied ? (
                    <Check className="w-3.5 h-3.5" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                  {codesCopied ? "Copied!" : "Copy all codes + link"}
                </button>
                <button
                  onClick={handleResetApprovals}
                  disabled={approvalBusy}
                  className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-xl text-amber-400 bg-amber-900/20 border border-amber-700/40 hover:bg-amber-900/30 transition-all cursor-pointer disabled:opacity-50"
                >
                  <RotateCcw className="w-3.5 h-3.5" /> Reset all approvals
                </button>
              </div>
            </>
          )}

          {/* Flagged entries */}
          {unresolvedFlags.length > 0 && (
            <div className="px-5 pb-5">
              <div className="bg-slate-900 border border-slate-700 rounded-xl overflow-hidden">
                <div className="flex items-center gap-2 px-4 py-3 border-b border-slate-700">
                  <Flag className="w-4 h-4 text-red-400" />
                  <p className="text-sm font-bold text-slate-300">
                    Flagged Entries
                  </p>
                  <span className="ml-auto text-xs font-mono text-slate-500">
                    {unresolvedFlags.length} to resolve
                  </span>
                </div>
                <div className="grid grid-cols-12 gap-2 px-4 py-2 text-[10px] font-bold text-slate-500 uppercase tracking-widest border-b border-slate-700/50">
                  <span className="col-span-3">Matric</span>
                  <span className="col-span-3">Reviewer</span>
                  <span className="col-span-4">Reason</span>
                  <span className="col-span-2"></span>
                </div>
                {unresolvedFlags.map((f) => (
                  <div
                    key={f.id}
                    className="grid grid-cols-12 gap-2 px-4 py-3 items-center border-b border-slate-700/40 last:border-0"
                  >
                    <span className="col-span-3 font-mono text-xs text-slate-300 truncate">
                      {f.matric}
                    </span>
                    <span className="col-span-3 text-xs text-slate-400 truncate">
                      {f.reviewer}
                    </span>
                    <span className="col-span-4 text-xs text-amber-300 truncate">
                      {f.reason}
                    </span>
                    <div className="col-span-2 flex justify-end">
                      <button
                        onClick={() => handleResolveFlag(f.id, f.matric)}
                        disabled={approvalBusy}
                        className="text-blue-400 hover:text-blue-300 text-xs font-bold transition-colors cursor-pointer disabled:opacity-50"
                      >
                        Resolve
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Lock registry — gated on all approved + no unresolved flags */}
          {rosterApproval.totalCount > 0 && (
            <div className="px-5 pb-5">
              <button
                onClick={handleLockRegistry}
                disabled={
                  approvalBusy ||
                  !rosterApproval.allApproved ||
                  rosterApproval.hasUnresolvedFlags ||
                  electionConfig.registryLocked
                }
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3.5 rounded-xl flex items-center justify-center gap-2 transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              >
                <Lock className="w-4 h-4" />
                {electionConfig.registryLocked
                  ? "Registry Locked"
                  : rosterApproval.allApproved && !rosterApproval.hasUnresolvedFlags
                  ? "Lock Registry"
                  : "Lock Registry — awaiting approvals"}
              </button>
            </div>
          )}
        </div>
      )}

      {/* Org voter URL */}
      <div className="bg-slate-900 border border-slate-700 rounded-2xl p-4 flex items-center gap-3 flex-wrap">
        <div className="flex-1 min-w-0">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1">
            Voter URL
          </p>
          <p className="text-sm font-mono text-blue-400 truncate">{voterUrl}</p>
        </div>
        <button
          onClick={handleCopy}
          title={copied ? "Copied!" : "Copy voter URL to clipboard"}
          className={`flex items-center gap-2 text-xs font-bold px-3 py-2 rounded-xl border transition-all cursor-pointer shrink-0 ${
            copied
              ? "bg-green-500/20 text-green-400 border-green-500/30"
              : "bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700"
          }`}
        >
          {copied ? (
            <Check className="w-3.5 h-3.5" />
          ) : (
            <Copy className="w-3.5 h-3.5" />
          )}
          {copied ? "Copied!" : "Copy"}
        </button>
      </div>

      {/* Org observer URL */}
      <div className="bg-slate-900 border border-slate-700 rounded-2xl p-4 flex items-center gap-3 flex-wrap">
        <div className="flex-1 min-w-0">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1">
            Observer URL
          </p>
          <p className="text-sm font-mono text-teal-400 truncate">
            {observerUrl}
          </p>
        </div>
        <button
          onClick={handleCopyObs}
          title={copiedObs ? "Copied!" : "Copy observer URL to clipboard"}
          className={`flex items-center gap-2 text-xs font-bold px-3 py-2 rounded-xl border transition-all cursor-pointer shrink-0 ${
            copiedObs
              ? "bg-green-500/20 text-green-400 border-green-500/30"
              : "bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700"
          }`}
        >
          {copiedObs ? (
            <Check className="w-3.5 h-3.5" />
          ) : (
            <Copy className="w-3.5 h-3.5" />
          )}
          {copiedObs ? "Copied!" : "Copy"}
        </button>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          ["Registered", voters.length, "text-white", "all"],
          ["Accredited", accredited, "text-blue-400", "accredited"],
          ["Voted", voted.length, "text-green-400", "voted"],
          ["Pending", pending.length, "text-amber-400", "pending"],
        ].map(([l, v, c, f]) => (
          <button
            key={l}
            onClick={() => setFilter(f)}
            className={`bg-slate-800 rounded-2xl p-5 border text-left hover:border-slate-500 transition-colors cursor-pointer ${
              filter === f ? "border-blue-500" : "border-slate-700"
            }`}
          >
            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">
              {l}
            </p>
            <p className={`text-3xl font-mono font-bold ${c}`}>{v}</p>
          </button>
        ))}
      </div>

      {/* Turnout bar */}
      <div className="bg-slate-800 rounded-2xl p-5 border border-slate-700">
        <div className="flex justify-between items-center mb-2">
          <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">
            Voter Turnout
          </p>
          <p className="text-sm font-mono font-bold text-white">{pct}%</p>
        </div>
        <div className="w-full bg-slate-700 rounded-full h-3">
          <div
            className="bg-gradient-to-r from-green-500 to-emerald-400 h-3 rounded-full transition-all duration-700"
            style={{ width: `${pct}%` }}
          />
        </div>
      </div>

      {/* Actions */}
      {/* Upload mode toggle + actions */}
      <div className="space-y-3">
        {/* Verified-template notice */}
        <div className="flex items-start gap-3 p-3 bg-slate-800 border border-slate-700 rounded-xl text-xs text-slate-400">
          <ShieldCheck className="w-4 h-4 text-blue-400 flex-shrink-0 mt-0.5" />
          <span>
            Only files downloaded from{" "}
            <span className="text-slate-300 font-bold">Download Template</span>{" "}
            can be uploaded. The system verifies each file's signature before
            accepting it.
          </span>
        </div>

        {/* Append vs Replace toggle */}
        <div className="flex items-center gap-3 bg-slate-800 rounded-xl p-3 border border-slate-700">
          <div className="flex-1">
            <p className="text-sm font-bold text-white">
              {replaceMode ? "Replace roster" : "Add to roster"}
            </p>
            <p className="text-xs text-slate-400 mt-0.5">
              {replaceMode
                ? "Clears all unvoted entries and uploads fresh — use for a new election"
                : "Adds new voters to the existing roster — duplicates are skipped"}
            </p>
          </div>
          <button
            onClick={() => setReplaceMode((v) => !v)}
            className={`relative w-11 h-6 rounded-full transition-colors cursor-pointer shrink-0 ${
              replaceMode ? "bg-amber-500" : "bg-slate-600"
            }`}
          >
            <span
              className={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow transition-transform duration-200 ${
                replaceMode ? "translate-x-5" : "translate-x-0"
              }`}
            />
          </button>
        </div>

        {/* Download template + Upload roster */}
        <div className="flex gap-3">
          <button
            onClick={handleDownloadTemplate}
            className="flex-1 bg-slate-700 hover:bg-slate-600 text-slate-300 font-bold py-3 px-4 rounded-xl flex items-center justify-center gap-2 border border-slate-600 transition-colors cursor-pointer"
          >
            <FileDown className="w-4 h-4" /> Download Template
          </button>
          <label
            className={`flex-1 text-white font-bold py-3 px-4 rounded-xl cursor-pointer flex items-center justify-center gap-2 transition-colors ${
              uploading
                ? "bg-slate-600 cursor-not-allowed"
                : replaceMode
                ? "bg-amber-600 hover:bg-amber-500"
                : "bg-blue-600 hover:bg-blue-700"
            }`}
          >
            {uploading ? (
              <VBLoader size="sm" />
            ) : (
              <>
                <Upload className="w-4 h-4" />
                {replaceMode ? "Upload (Replace)" : "Upload Roster"}
              </>
            )}
            <input
              type="file"
              accept=".csv"
              onChange={upload}
              className="hidden"
              disabled={uploading}
            />
          </label>
        </div>

        {/* Export current list (unchanged — reference only) */}
        <button
          onClick={exportCSV}
          className="w-full bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold py-2.5 px-4 rounded-xl flex items-center justify-center gap-2 border border-slate-700 transition-colors cursor-pointer text-sm"
        >
          <FileDown className="w-4 h-4" /> Export Current List
        </button>
      </div>

      {/* Empty state — shown before any roster is uploaded */}
      {voters.length === 0 && (
        <div className="bg-slate-800 border border-dashed border-slate-600 rounded-2xl p-10 text-center">
          <div className="w-16 h-16 bg-slate-700 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Users className="w-8 h-8 text-slate-500" />
          </div>
          <h3 className="text-white font-black mb-2">No voters yet</h3>
          <p className="text-slate-400 text-sm mb-6 max-w-sm mx-auto">
            Upload a CSV file to add eligible voters to the roster. Voters must
            be on the roster to register and vote.
          </p>

          {/* CSV format reminder */}
          <div className="bg-slate-900 rounded-xl p-4 text-left max-w-xs mx-auto mb-6">
            <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-2">
              CSV format
            </p>
            <code className="text-xs text-green-400 font-mono leading-relaxed block">
              matric,name,email
              <br />
              U/25/001,Amina Yusuf,amina@gmail.com
              <br />
              U/25/002,Emeka Obi,emeka@gmail.com
            </code>
          </div>

          <label className="bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 px-6 rounded-xl inline-flex items-center gap-2 cursor-pointer transition-colors">
            <Upload className="w-4 h-4" /> Upload CSV Roster
            <input
              type="file"
              accept=".csv"
              onChange={upload}
              className="hidden"
            />
          </label>
        </div>
      )}

      {/* Table */}
      <div className="bg-slate-800 rounded-2xl border border-slate-700 overflow-hidden">
        <div className="p-4 border-b border-slate-700 space-y-3">
          <div className="flex gap-2 flex-wrap items-center">
            {[
              ["all", "All"],
              ["accredited", "Accredited"],
              ["voted", "Voted"],
              ["pending", "Pending"],
            ].map(([v, l]) => (
              <button
                key={v}
                onClick={() => setFilter(v)}
                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-colors cursor-pointer ${
                  filter === v
                    ? "bg-blue-600 text-white"
                    : "bg-slate-700 text-slate-400 hover:bg-slate-600"
                }`}
              >
                {l}
              </button>
            ))}
            <div className="flex-1 min-w-40 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500" />
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search…"
                className="w-full bg-slate-900 border border-slate-600 rounded-lg py-1.5 pl-8 pr-3 text-sm outline-none text-white placeholder:text-slate-600 focus:border-blue-500"
              />
            </div>
          </div>
        </div>

        <div className="grid grid-cols-12 gap-2 px-4 py-2 text-xs font-bold text-slate-500 uppercase tracking-widest border-b border-slate-700/50">
          <span className="col-span-3">Matric</span>
          <span className="col-span-4">Name</span>
          <span className="col-span-3">Email</span>
          <span className="col-span-1 text-center">✓</span>
          <span className="col-span-1"></span>
        </div>

        <div className="max-h-72 overflow-y-auto">
          {filtered.length === 0 ? (
            <p className="text-slate-500 text-sm text-center py-10">
              No voters match.
            </p>
          ) : (
            filtered.map((u) => (
              <div
                key={u.matric}
                className="grid grid-cols-12 gap-2 px-4 py-3 items-center hover:bg-slate-700/30 border-b border-slate-700/30 last:border-0 group"
              >
                <span className="col-span-3 font-mono text-sm text-slate-300 truncate">
                  {u.matric}
                </span>
                <span className="col-span-4 text-sm font-bold text-white truncate">
                  {u.name}
                </span>
                <span className="col-span-3 text-xs text-slate-500 truncate">
                  {u.email ?? "—"}
                </span>
                <div className="col-span-1 flex justify-center">
                  {u.hasVoted ? (
                    <UserCheck className="w-4 h-4 text-green-400" />
                  ) : (
                    <UserX className="w-4 h-4 text-slate-600" />
                  )}
                </div>
                <div className="col-span-1 flex justify-center">
                  {!u.hasVoted && (
                    <button
                      onClick={() => handleRemove(u)}
                      className="text-slate-600 hover:text-red-400 text-xs opacity-0 group-hover:opacity-100 transition-all cursor-pointer font-bold"
                    >
                      ✕
                    </button>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
        <div className="px-4 py-2 border-t border-slate-700 text-xs text-slate-600">
          Showing {filtered.length} of {voters.length}
        </div>
      </div>
    </div>
  );
}
