import { useState } from "react";
import {
  Upload,
  Users,
  FileDown,
  Search,
  Copy,
  Check,
  ClipboardList,
  Lock,
  Flag,
  UserPlus,
  RotateCcw,
  ShieldCheck,
} from "lucide-react";
import { useApp } from "../../context/AppContext";
import { buildVoterCSV, downloadCSV, getTurnout } from "../../utils";
import {
  uploadRoster,
  downloadRosterTemplate,
  fetchVoters,
  removeVoter,
  resolveRosterFlag,
  regenerateReviewCodes,
  updateElectionConfig,
  addRosterReviewer,
  removeRosterReviewer,
} from "../../api";
import VBLoader from "../ui/VBLoader";

export default function VotersTab() {
  const {
    users,
    setUsers,
    accessToken,
    orgSlug,
    showAlert,
    showConfirm,
    addLog,
    electionConfig,
    setElectionConfig,
    rosterApproval,
    refreshRosterApproval,
    mapVoter,
  } = useApp();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const [uploading, setUploading] = useState(false);
  const [replaceMode, setReplaceMode] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copiedObs, setCopiedObs] = useState(false);
  const [codesCopied, setCodesCopied] = useState(false);
  const [copiedId, setCopiedId] = useState(null);
  const [approvalBusy, setApprovalBusy] = useState(false);
  const [reviewerName, setReviewerName] = useState("");

  const rosterActive = electionConfig.votingMode === "CLOSED";

  const voterUrl = `${window.location.origin}/vote/${orgSlug}`;
  const observerUrl = `${window.location.origin}/observer/login?slug=${orgSlug}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(voterUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleCopyObs = () => {
    navigator.clipboard.writeText(observerUrl).then(() => {
      setCopiedObs(true);
      setTimeout(() => setCopiedObs(false), 2000);
    });
  };

  const voters = users.filter((u) => u.role !== "ADMIN");
  const voted = voters.filter((u) => u.hasVoted);
  const pending = voters.filter((u) => !u.hasVoted);
  const { accredited } = getTurnout(users);

  const filtered = voters.filter((u) => {
    const matchText =
      u.matric.toLowerCase().includes(search.toLowerCase()) ||
      u.name.toLowerCase().includes(search.toLowerCase());
    const matchFilter =
      filter === "all" ||
      (filter === "accredited" && u.email) ||
      (filter === "voted" && u.hasVoted) ||
      (filter === "pending" && !u.hasVoted);
    return matchText && matchFilter;
  });

  const exportCSV = () => downloadCSV(buildVoterCSV(voters), "registry.csv");

  // Download the official signed template.
  const handleDownloadTemplate = async () => {
    try {
      const csvText = await downloadRosterTemplate(accessToken, orgSlug);
      const blob = new Blob([csvText], { type: "text/csv" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `roster-template-${orgSlug}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      showAlert("Download Failed", err.message);
    }
  };

  // Upload the raw (signed) CSV → backend verifies the signature before parsing.
  const upload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    e.target.value = "";
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const csvRaw = ev.target.result;

      // Fast client-side check — the backend does the real cryptographic verify.
      if (!csvRaw.includes("#VB-SIGNED")) {
        showAlert(
          "Invalid Template",
          "This file was not generated by Virtual Ballot. Please click 'Download Template' to get the official template, fill it in, and upload that file."
        );
        return;
      }

      setUploading(true);
      try {
        const result = await uploadRoster(
          csvRaw,
          accessToken,
          orgSlug,
          replaceMode
        );
        // Refresh the voter list from the backend (source of truth).
        try {
          const data = await fetchVoters(accessToken, orgSlug);
          setUsers((data.voters || []).map(mapVoter));
        } catch {
          /* non-fatal — the upload succeeded; the next poll refreshes the list */
        }

        addLog(
          replaceMode
            ? `Roster replaced — ${result.inserted} voters loaded`
            : `Roster updated — ${result.inserted} voters added`,
          "registry"
        );
        showAlert(
          replaceMode ? "Roster Replaced" : "Upload Success",
          replaceMode
            ? `${result.inserted} voters loaded. Voters who already voted were preserved.`
            : `${result.inserted} voters added to roster. ${result.skipped} skipped (duplicates).`
        );
        // Closed elections: refresh the review panel (a changed roster may
        // reset the approval status). Open elections are unaffected.
        if (rosterActive) refreshRosterApproval();
      } catch (err) {
        showAlert("Upload Failed", err.message);
      } finally {
        setUploading(false);
      }
    };
    reader.readAsText(file);
  };

  const handleRemove = async (voter) => {
    try {
      await removeVoter(voter.id, accessToken, orgSlug);
      setUsers((prev) => prev.filter((u) => u.matric !== voter.matric));
      addLog(`Voter ${voter.matric} removed from roster`, "registry");
    } catch (err) {
      showAlert("Cannot Remove", err.message);
    }
  };

  // ── Roster review panel helpers ─────────────────────────────────────────────
  // Flatten every flag with the reviewer who raised it for the flags table.
  const allFlags = rosterApproval.approvals.flatMap((a) =>
    (a.flags || []).map((f) => ({ ...f, reviewer: a.reviewerName }))
  );
  const unresolvedFlags = allFlags.filter((f) => !f.resolved);

  const handleAddReviewer = async () => {
    const name = reviewerName.trim();
    if (!name) return;
    setApprovalBusy(true);
    try {
      await addRosterReviewer(name, accessToken, orgSlug);
      await refreshRosterApproval();
      addLog(`Committee member '${name}' added to roster review panel`, "registry");
      setReviewerName("");
    } catch (err) {
      showAlert("Could Not Add Reviewer", err.message);
    } finally {
      setApprovalBusy(false);
    }
  };

  const handleRemoveReviewer = (reviewer) => {
    showConfirm(
      "Remove committee member?",
      `Remove ${reviewer.reviewerName} from the review panel? Their review code will stop working.`,
      async () => {
        setApprovalBusy(true);
        try {
          await removeRosterReviewer(reviewer.id, accessToken, orgSlug);
          await refreshRosterApproval();
          addLog(
            `Committee member '${reviewer.reviewerName}' removed from roster review panel`,
            "registry"
          );
        } catch (err) {
          showAlert("Could Not Remove", err.message);
        } finally {
          setApprovalBusy(false);
        }
      }
    );
  };

  const copyAllCodes = () => {
    const lines = rosterApproval.approvals
      .map((a) => `${a.reviewerName}: ${a.reviewCode}`)
      .join("\n");
    const text = `Virtual Ballot — Roster Review Panel
Please use your personal code to review the voter list.

Review Portal: ${window.location.origin}/roster-review

${lines}`;
    navigator.clipboard.writeText(text).then(() => {
      setCodesCopied(true);
      setTimeout(() => setCodesCopied(false), 2500);
    });
  };

  // Copy one reviewer's personal invite (portal link + their code) to send individually.
  const copyReviewer = (a) => {
    const text = `Hi ${a.reviewerName}, please review and approve the voter list for the election.

Review Portal: ${window.location.origin}/roster-review
Your code: ${a.reviewCode}`;
    navigator.clipboard.writeText(text).then(() => {
      setCopiedId(a.id);
      setTimeout(() => setCopiedId((cur) => (cur === a.id ? null : cur)), 2500);
    });
  };

  const handleResetApprovals = () => {
    showConfirm(
      "Reset all approvals?",
      "This sets every committee member back to pending. They keep their codes but must review and approve again. Continue?",
      async () => {
        setApprovalBusy(true);
        try {
          await regenerateReviewCodes(accessToken, orgSlug);
          await refreshRosterApproval();
          addLog("Roster approvals reset — all committee members must re-approve", "registry");
        } catch (err) {
          showAlert("Reset Failed", err.message);
        } finally {
          setApprovalBusy(false);
        }
      }
    );
  };

  const handleResolveFlag = async (flagId, matric) => {
    setApprovalBusy(true);
    try {
      await resolveRosterFlag(flagId, accessToken, orgSlug);
      await refreshRosterApproval();
      addLog(`Flag on matric ${matric} resolved`, "admin");
    } catch (err) {
      showAlert("Could Not Resolve", err.message);
    } finally {
      setApprovalBusy(false);
    }
  };

  const handleLockRegistry = () => {
    if (!rosterApproval.allApproved || rosterApproval.hasUnresolvedFlags) return;
    showConfirm(
      "Lock the registry?",
      "All committee members have approved the voter list. Locking the registry finalises it so it can no longer be edited before voting. Continue?",
      async () => {
        setApprovalBusy(true);
        try {
          await updateElectionConfig(
            { registryLocked: true },
            accessToken,
            orgSlug
          );
          setElectionConfig((prev) => ({ ...prev, registryLocked: true }));
          addLog("Registry locked — roster approved by all committee members", "registry");
          showAlert(
            "Registry Locked",
            "The voter registry is now locked. You can start the election from the Election tab."
          );
        } catch (err) {
          showAlert("Could Not Lock Registry", err.message);
        } finally {
          setApprovalBusy(false);
        }
      }
    );
  };

  const pendingApprovals =
    rosterApproval.totalCount - rosterApproval.approvedCount;
  const lockReady =
    rosterApproval.allApproved && !rosterApproval.hasUnresolvedFlags;
  const lockHint = lockReady
    ? "All reviewers have approved — locking finalises the roster before voting."
    : `Waiting on ${
        pendingApprovals > 0
          ? `${pendingApprovals} approval${pendingApprovals !== 1 ? "s" : ""}`
          : ""
      }${pendingApprovals > 0 && unresolvedFlags.length > 0 ? " and " : ""}${
        unresolvedFlags.length > 0
          ? `${unresolvedFlags.length} unresolved flag${
              unresolvedFlags.length !== 1 ? "s" : ""
            }`
          : ""
      } — the registry locks once every reviewer approves and all flags are resolved.`;

  const statTiles = [
    { label: "Registered", value: voters.length, f: "all", hint: "Show all" },
    { label: "Accredited", value: accredited, f: "accredited", hint: "Filter" },
    { label: "Voted", value: voted.length, f: "voted", hint: "Filter" },
    { label: "Pending", value: pending.length, f: "pending", hint: "Filter" },
  ];

  return (
    <div className="space-y-4">
      {/* ── Roster review panel (closed elections only) ────────────────────── */}
      {rosterActive && (
        <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
          <div className="flex items-center gap-2 px-5 py-3 border-b border-slate-100 flex-wrap">
            <h4 className="text-[13px] font-semibold text-slate-900 flex items-center gap-2">
              <ClipboardList className="w-4 h-4 text-blue-600" /> Roster review
              panel
            </h4>
            <span className="ml-auto text-[11px] text-slate-400">
              Committee sign-off gates the election start
            </span>
          </div>

          <div className="p-5 pb-4">
            {/* Add a committee member */}
            <div className="flex gap-3">
              <input
                value={reviewerName}
                onChange={(e) => setReviewerName(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleAddReviewer()}
                placeholder="Committee member's full name (e.g. Kabir Marzooq)"
                className="flex-1 min-h-[44px] text-[13px] text-slate-900 bg-white border border-slate-300 rounded-lg px-3.5 outline-none placeholder:text-slate-400 focus:border-blue-500 focus:ring-[3px] focus:ring-blue-100 transition-all"
              />
              <button
                onClick={handleAddReviewer}
                disabled={approvalBusy || !reviewerName.trim()}
                title="Add this person to the review panel"
                className="inline-flex items-center gap-2 min-h-[44px] px-4 text-[13px] font-semibold text-white bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 disabled:text-slate-400 disabled:cursor-not-allowed rounded-lg shadow-sm transition-all cursor-pointer whitespace-nowrap"
              >
                <UserPlus className="w-4 h-4" /> Add reviewer
              </button>
            </div>

            {/* Progress */}
            {rosterApproval.totalCount > 0 && (
              <div className="mt-4">
                <div className="flex justify-between items-baseline mb-2">
                  <span className="text-[13px] font-semibold text-slate-900">
                    {rosterApproval.approvedCount} of{" "}
                    {rosterApproval.totalCount} reviewers have approved
                  </span>
                  <span className="font-mono text-xs font-semibold text-slate-600 tabular-nums">
                    {Math.round(
                      (rosterApproval.approvedCount /
                        rosterApproval.totalCount) *
                        100
                    )}
                    %
                  </span>
                </div>
                <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-600 rounded-full transition-all duration-700"
                    style={{
                      width: `${
                        (rosterApproval.approvedCount /
                          rosterApproval.totalCount) *
                        100
                      }%`,
                    }}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Reviewer table */}
          {rosterApproval.approvals.length === 0 ? (
            <p className="text-xs leading-[18px] text-slate-600 text-center px-5 pb-5">
              No committee members yet. Add reviewers, then send each person
              their code and the review portal link.
            </p>
          ) : (
            <>
              <div className="grid grid-cols-12 gap-2 px-5 py-2 text-[10px] font-semibold text-slate-600 uppercase tracking-[0.08em] bg-slate-50 border-y border-slate-100">
                <span className="col-span-3">Reviewer</span>
                <span className="col-span-2">Code</span>
                <span className="col-span-2">Status</span>
                <span className="col-span-2">Approved</span>
                <span className="col-span-3 text-right">Actions</span>
              </div>
              <div>
                {rosterApproval.approvals.map((a) => (
                  <div
                    key={a.id}
                    className="grid grid-cols-12 gap-2 px-5 py-2.5 items-center border-b border-slate-100 last:border-0 hover:bg-slate-50 transition-colors"
                  >
                    <span className="col-span-3 text-[13px] font-semibold text-slate-900 truncate">
                      {a.reviewerName}
                    </span>
                    <span className="col-span-2">
                      <span className="font-mono text-[11px] font-semibold tracking-[0.1em] bg-slate-100 text-slate-800 px-2 py-1 rounded-md">
                        {a.reviewCode}
                      </span>
                    </span>
                    <span className="col-span-2">
                      {a.approved ? (
                        <span className="inline-flex items-center gap-1 text-[10px] font-semibold bg-green-50 text-green-600 border border-green-200 px-2.5 py-0.5 rounded-full">
                          ✓ Approved
                        </span>
                      ) : (
                        <span className="inline-flex items-center text-[10px] font-semibold bg-amber-50 text-amber-800 border border-amber-200 px-2.5 py-0.5 rounded-full">
                          Pending
                        </span>
                      )}
                    </span>
                    <span className="col-span-2 font-mono text-[11px] text-slate-600">
                      {a.approvedAt
                        ? new Date(a.approvedAt).toLocaleTimeString([], {
                            hour: "2-digit",
                            minute: "2-digit",
                          })
                        : "—"}
                    </span>
                    <div className="col-span-3 flex justify-end items-center gap-1">
                      <button
                        onClick={() => copyReviewer(a)}
                        title="Copy this reviewer's link + code"
                        className={`inline-flex items-center gap-1.5 text-xs font-semibold px-2 py-1.5 rounded-md transition-all cursor-pointer ${
                          copiedId === a.id
                            ? "text-green-600"
                            : "text-slate-600 hover:text-blue-700 hover:bg-blue-50"
                        }`}
                      >
                        {copiedId === a.id ? (
                          <>
                            <Check className="w-3 h-3" /> Copied
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3" /> Copy invite
                          </>
                        )}
                      </button>
                      {!a.approved && (
                        <button
                          onClick={() => handleRemoveReviewer(a)}
                          disabled={approvalBusy}
                          title="Remove this reviewer from the panel"
                          className="text-xs font-semibold text-slate-600 hover:text-red-600 hover:bg-red-50 px-2 py-1.5 rounded-md transition-all cursor-pointer disabled:opacity-50"
                        >
                          Remove
                        </button>
                      )}
                    </div>
                  </div>
                ))}
              </div>

              {/* Panel actions */}
              <div className="flex flex-wrap gap-3 px-5 py-4 border-t border-slate-100">
                <button
                  onClick={copyAllCodes}
                  title="Copy every reviewer's code plus the portal link"
                  className={`inline-flex items-center gap-2 text-xs font-semibold min-h-[36px] px-3 rounded-lg border transition-all cursor-pointer ${
                    codesCopied
                      ? "bg-green-50 text-green-600 border-green-200"
                      : "bg-white text-slate-600 border-slate-300 hover:border-slate-400 hover:text-slate-800"
                  }`}
                >
                  {codesCopied ? (
                    <Check className="w-3 h-3" />
                  ) : (
                    <Copy className="w-3 h-3" />
                  )}
                  {codesCopied ? "Copied" : "Copy all codes + link"}
                </button>
                <button
                  onClick={handleResetApprovals}
                  disabled={approvalBusy}
                  title="Set every reviewer back to pending"
                  className="inline-flex items-center gap-2 text-xs font-semibold min-h-[36px] px-3 rounded-lg bg-amber-50 text-amber-800 border border-amber-200 hover:bg-amber-100 transition-all cursor-pointer disabled:opacity-50"
                >
                  <RotateCcw className="w-3 h-3" /> Reset all approvals
                </button>
              </div>
            </>
          )}

          {/* Flagged entries */}
          {unresolvedFlags.length > 0 && (
            <div className="mx-5 mb-5 border border-amber-200 rounded-xl overflow-hidden">
              <div className="flex items-center gap-2 bg-amber-50 px-4 py-2.5 text-xs font-semibold text-amber-800">
                <Flag className="w-3.5 h-3.5" /> Flagged entries ·{" "}
                {unresolvedFlags.length} to resolve
              </div>
              <div className="grid grid-cols-12 gap-2 px-4 py-2 text-[10px] font-semibold text-slate-600 uppercase tracking-[0.08em] border-b border-slate-100">
                <span className="col-span-3">Matric</span>
                <span className="col-span-3">Raised by</span>
                <span className="col-span-4">Reason</span>
                <span className="col-span-2"></span>
              </div>
              {unresolvedFlags.map((f) => (
                <div
                  key={f.id}
                  className="grid grid-cols-12 gap-2 px-4 py-2.5 items-center border-b border-slate-100 last:border-0"
                >
                  <span className="col-span-3 font-mono text-xs text-slate-800 truncate">
                    {f.matric}
                  </span>
                  <span className="col-span-3 text-xs text-slate-600 truncate">
                    {f.reviewer}
                  </span>
                  <span className="col-span-4 text-xs text-amber-800 truncate">
                    {f.reason}
                  </span>
                  <div className="col-span-2 flex justify-end">
                    <button
                      onClick={() => handleResolveFlag(f.id, f.matric)}
                      disabled={approvalBusy}
                      title="Mark this flag as resolved"
                      className="text-xs font-semibold min-h-[32px] px-3 rounded-lg bg-white text-slate-600 border border-slate-300 hover:border-slate-400 hover:text-slate-800 transition-all cursor-pointer disabled:opacity-50"
                    >
                      Resolve
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Lock registry — gated on all approved + no unresolved flags */}
          {rosterApproval.totalCount > 0 && (
            <div className="px-5 pb-5 pt-4 border-t border-slate-100">
              {electionConfig.registryLocked ? (
                <div className="flex items-center justify-center gap-2 min-h-[44px] bg-green-50 border border-green-200 rounded-lg text-green-600 text-[13px] font-semibold">
                  <Lock className="w-3.5 h-3.5" /> Registry locked
                </div>
              ) : (
                <>
                  <button
                    onClick={handleLockRegistry}
                    disabled={approvalBusy || !lockReady}
                    title="Finalise the roster so it can no longer be edited"
                    className="w-full min-h-[44px] bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 disabled:text-slate-400 disabled:cursor-not-allowed text-white font-semibold text-[13px] rounded-lg shadow-sm flex items-center justify-center gap-2 transition-all cursor-pointer"
                  >
                    <Lock className="w-3.5 h-3.5" /> Lock registry
                  </button>
                  <p className="text-[11px] leading-4 text-slate-600 text-center mt-2">
                    {lockHint}
                  </p>
                </>
              )}
            </div>
          )}
        </div>
      )}

      {/* ── Share links ─────────────────────────────────────────────────────── */}
      <div className="grid sm:grid-cols-2 gap-3">
        <div className="flex items-center gap-3 bg-white border border-blue-200 rounded-xl px-4 py-3">
          <div className="flex-1 min-w-0">
            <p className="text-[10px] font-semibold text-blue-700 uppercase tracking-[0.1em] mb-0.5">
              Voter URL
            </p>
            <p className="font-mono text-[11px] text-slate-800 truncate">
              {voterUrl}
            </p>
          </div>
          <button
            onClick={handleCopy}
            title="Copy the voter URL"
            className={`text-xs font-semibold min-h-[36px] px-3 rounded-lg transition-all cursor-pointer shrink-0 ${
              copied
                ? "bg-green-50 text-green-600 border border-green-200"
                : "bg-blue-600 hover:bg-blue-700 text-white"
            }`}
          >
            {copied ? "✓ Copied" : "Copy"}
          </button>
        </div>
        <div className="flex items-center gap-3 bg-white border border-slate-200 rounded-xl px-4 py-3">
          <div className="flex-1 min-w-0">
            <p className="text-[10px] font-semibold text-slate-600 uppercase tracking-[0.1em] mb-0.5">
              Observer URL
            </p>
            <p className="font-mono text-[11px] text-slate-800 truncate">
              {observerUrl}
            </p>
          </div>
          <button
            onClick={handleCopyObs}
            title="Copy the observer URL"
            className={`text-xs font-semibold min-h-[36px] px-3 rounded-lg transition-all cursor-pointer shrink-0 ${
              copiedObs
                ? "bg-green-50 text-green-600 border border-green-200"
                : "bg-white text-slate-600 border border-slate-300 hover:border-slate-400 hover:text-slate-800"
            }`}
          >
            {copiedObs ? "✓ Copied" : "Copy"}
          </button>
        </div>
      </div>

      {/* ── Stat tiles double as filters ───────────────────────────────────── */}
      {voters.length > 0 && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {statTiles.map((s) => {
            const on = filter === s.f;
            return (
              <button
                key={s.f}
                onClick={() => setFilter(s.f)}
                title={`Filter the table: ${s.label.toLowerCase()}`}
                className={`text-left rounded-xl border px-4 py-3 transition-all cursor-pointer ${
                  on
                    ? "bg-blue-50 border-blue-600 ring-1 ring-blue-600"
                    : "bg-white border-slate-200 hover:border-slate-300"
                }`}
              >
                <p
                  className={`text-[11px] font-semibold uppercase tracking-[0.08em] ${
                    on ? "text-blue-700" : "text-slate-600"
                  }`}
                >
                  {s.label}
                </p>
                <p className="text-2xl leading-8 font-semibold text-slate-900 tabular-nums mt-0.5">
                  {s.value}
                </p>
                <p
                  className={`text-[10px] mt-0.5 ${
                    on ? "text-blue-700" : "text-slate-400"
                  }`}
                >
                  {on ? "Filtering ✓" : s.hint}
                </p>
              </button>
            );
          })}
        </div>
      )}

      {/* ── Empty state (no roster yet) ────────────────────────────────────── */}
      {voters.length === 0 && (
        <div className="bg-white border border-dashed border-slate-300 rounded-xl p-10 text-center">
          <div className="w-14 h-14 bg-slate-100 rounded-xl flex items-center justify-center mx-auto mb-3 text-slate-400">
            <Users className="w-6 h-6" />
          </div>
          <h4 className="text-base font-semibold text-slate-900">
            No voters yet
          </h4>
          <p className="text-[13px] leading-5 text-slate-600 mt-1 max-w-sm mx-auto">
            Download the official template, fill it in, and upload it below.
            Voters must be on the roster to activate an account and vote.
          </p>
          <div className="bg-slate-50 border border-slate-200 rounded-lg px-4 py-3 max-w-xs mx-auto mt-4 text-left">
            <p className="text-[10px] font-semibold text-slate-600 uppercase tracking-[0.1em] mb-1.5">
              Template columns
            </p>
            <code className="font-mono text-[11px] leading-[18px] text-slate-800 block whitespace-pre">
              {"matric,name,email\nU/25/001,Amina Yusuf,amina@edu.ng\nU/25/002,Emeka Obi,emeka@edu.ng"}
            </code>
          </div>
        </div>
      )}

      {/* ── Roster upload ──────────────────────────────────────────────────── */}
      <div className="bg-white border border-slate-200 rounded-xl p-5">
        <p className="text-[11px] font-semibold text-slate-600 uppercase tracking-[0.08em] mb-3">
          Roster upload
        </p>
        <div className="flex gap-2.5 bg-blue-50 border border-blue-200 rounded-lg px-3.5 py-2.5 text-xs leading-[18px] text-slate-800 mb-3">
          <ShieldCheck className="w-4 h-4 text-blue-600 shrink-0 mt-px" />
          <span>
            Only files downloaded from{" "}
            <span className="font-semibold">Download template</span> can be
            uploaded — each file carries a signature that is verified before
            any voter is added.
          </span>
        </div>

        {/* Append vs Replace */}
        <div
          className={`flex items-center gap-3 border rounded-xl px-4 py-3 mb-3 transition-colors ${
            replaceMode
              ? "bg-amber-50 border-amber-200"
              : "bg-white border-slate-200"
          }`}
        >
          <div className="flex-1 min-w-0">
            <p className="text-[13px] font-semibold text-slate-900">
              {replaceMode ? "Replace roster" : "Add to roster"}
            </p>
            <p
              className={`text-[11px] leading-4 mt-0.5 ${
                replaceMode ? "text-amber-800" : "text-slate-600"
              }`}
            >
              {replaceMode
                ? "Clears all unvoted entries and uploads fresh — voters who already voted are preserved"
                : "Adds new voters to the existing roster — duplicates are skipped"}
            </p>
          </div>
          <span
            className={`text-[11px] font-semibold shrink-0 ${
              replaceMode ? "text-amber-800" : "text-slate-600"
            }`}
          >
            {replaceMode ? "Replace" : "Add"}
          </span>
          <button
            onClick={() => setReplaceMode((v) => !v)}
            title={
              replaceMode
                ? "Switch back to add-to-roster mode"
                : "Switch to replace-roster mode"
            }
            className="w-11 h-11 flex items-center justify-center shrink-0 cursor-pointer"
          >
            <span
              className={`relative w-9 h-5 rounded-full transition-colors ${
                replaceMode ? "bg-amber-600" : "bg-slate-300"
              }`}
            >
              <span
                className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow-sm transition-all ${
                  replaceMode ? "left-[18px]" : "left-0.5"
                }`}
              />
            </span>
          </button>
        </div>

        <div className="flex gap-3">
          <button
            onClick={handleDownloadTemplate}
            title="Download the official signed CSV template"
            className="flex-1 min-h-[44px] bg-white text-slate-600 border border-slate-300 hover:border-slate-400 hover:text-slate-800 font-semibold text-[13px] rounded-lg flex items-center justify-center gap-2 transition-all cursor-pointer"
          >
            <FileDown className="w-4 h-4" /> Download template
          </button>
          <label
            title={
              replaceMode
                ? "Upload a signed CSV and replace the roster"
                : "Upload a signed CSV and add to the roster"
            }
            className={`flex-1 min-h-[44px] text-white font-semibold text-[13px] rounded-lg shadow-sm flex items-center justify-center gap-2 transition-all cursor-pointer ${
              uploading
                ? "bg-slate-200 text-slate-400 cursor-not-allowed"
                : replaceMode
                ? "bg-amber-600 hover:bg-amber-700"
                : "bg-blue-600 hover:bg-blue-700"
            }`}
          >
            {uploading ? (
              <VBLoader size="sm" />
            ) : (
              <>
                <Upload className="w-4 h-4" />
                {replaceMode ? "Upload & replace roster" : "Upload roster"}
              </>
            )}
            <input
              type="file"
              accept=".csv"
              onChange={upload}
              className="hidden"
              disabled={uploading}
            />
          </label>
        </div>

        {voters.length > 0 && (
          <button
            onClick={exportCSV}
            title="Download the current roster as CSV"
            className="w-full mt-3 min-h-[36px] bg-white text-slate-600 border border-slate-300 hover:border-slate-400 hover:text-slate-800 font-semibold text-xs rounded-lg flex items-center justify-center gap-2 transition-all cursor-pointer"
          >
            <FileDown className="w-3.5 h-3.5" /> Export current list
          </button>
        )}
      </div>

      {/* ── Voter table ────────────────────────────────────────────────────── */}
      {voters.length > 0 && (
        <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
          <div className="flex gap-2 flex-wrap items-center px-5 py-3 border-b border-slate-100">
            {[
              ["all", "All"],
              ["accredited", "Accredited"],
              ["voted", "Voted"],
              ["pending", "Pending"],
            ].map(([v, l]) => (
              <button
                key={v}
                onClick={() => setFilter(v)}
                title={`Show ${l.toLowerCase()} voters`}
                className={`text-xs font-semibold min-h-[32px] px-3.5 rounded-full border transition-all cursor-pointer ${
                  filter === v
                    ? "bg-blue-600 border-blue-600 text-white"
                    : "bg-white border-slate-300 text-slate-600 hover:border-slate-400"
                }`}
              >
                {l}
              </button>
            ))}
            <div className="flex-1 min-w-[180px] relative">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400 pointer-events-none" />
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search name or matric…"
                className="w-full min-h-[32px] text-xs text-slate-900 bg-white border border-slate-300 rounded-lg pl-8 pr-3 outline-none placeholder:text-slate-400 focus:border-blue-500 focus:ring-[3px] focus:ring-blue-100 transition-all"
              />
            </div>
          </div>

          <div className="grid grid-cols-12 gap-2 px-5 py-2 text-[10px] font-semibold text-slate-600 uppercase tracking-[0.08em] bg-slate-50 border-b border-slate-100">
            <span className="col-span-3">Matric</span>
            <span className="col-span-4">Name</span>
            <span className="col-span-3">Email</span>
            <span className="col-span-1 text-center">Voted</span>
            <span className="col-span-1"></span>
          </div>

          <div className="max-h-72 overflow-y-auto">
            {filtered.length === 0 ? (
              <p className="text-[13px] text-slate-400 text-center py-10">
                No voters match.
              </p>
            ) : (
              filtered.map((u) => (
                <div
                  key={u.matric}
                  className="grid grid-cols-12 gap-2 px-5 py-2.5 items-center border-b border-slate-100 last:border-0 hover:bg-slate-50 transition-colors group"
                >
                  <span className="col-span-3 font-mono text-xs text-slate-800 truncate">
                    {u.matric}
                  </span>
                  <span className="col-span-4 text-[13px] font-semibold text-slate-900 truncate">
                    {u.name}
                  </span>
                  <span className="col-span-3 text-xs text-slate-600 truncate">
                    {u.email ?? "—"}
                  </span>
                  <div className="col-span-1 flex justify-center">
                    {u.hasVoted ? (
                      <span className="w-[22px] h-[22px] rounded-full bg-green-50 border border-green-200 text-green-600 inline-flex items-center justify-center">
                        <Check className="w-3 h-3" strokeWidth={2.6} />
                      </span>
                    ) : (
                      <span className="text-slate-300 text-[13px]">—</span>
                    )}
                  </div>
                  <div className="col-span-1 flex justify-end">
                    {!u.hasVoted && (
                      <button
                        onClick={() => handleRemove(u)}
                        title={`Remove ${u.matric} from the roster`}
                        className="text-xs font-semibold text-slate-400 hover:text-red-600 hover:bg-red-50 px-2 py-1.5 rounded-md opacity-0 group-hover:opacity-100 transition-all cursor-pointer whitespace-nowrap"
                      >
                        ✕ Remove
                      </button>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
          <p className="px-5 py-2 border-t border-slate-100 text-[11px] text-slate-400">
            Showing {filtered.length} of {voters.length}
          </p>
        </div>
      )}
    </div>
  );
}
